# Generated by Django 3.2.3 on 2021-09-17 08:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmucthongbao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendanhmuc', models.CharField(default='', max_length=255, verbose_name='Tên Danh Mục ')),
                ('mota', models.CharField(default='', max_length=1000, verbose_name='Mô tả danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Thông Báo',
                'verbose_name_plural': 'Danh Mục Thông Báo',
            },
        ),
        migrations.CreateModel(
            name='Thongbao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(default='', max_length=255, verbose_name='Tiêu đề thông báo')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Thông Báo')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy Thông báo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_viewers', models.JSONField(blank=True, null=True)),
                ('viewers', models.JSONField(blank=True, null=True)),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdqttb.danhmucthongbao', verbose_name='Chọn Danh Mục')),
                ('phongban', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng ban Áp dụng -Nêu Công Ty thì không chọn ')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '0. Thông Báo',
                'verbose_name_plural': '0. Thông Báo',
            },
        ),
        migrations.CreateModel(
            name='Quytrinhphongban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenquytrinh', models.CharField(default='', max_length=255, verbose_name='Tên quy trình')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung quy trình')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy Thông báo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng ban áp dụng')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '6. Quy Trình Phòng Ban',
                'verbose_name_plural': '6. Quy Trình Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Quytrinhcongty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenquytrinh', models.CharField(default='', max_length=255, verbose_name='Tên quy trình')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung quy trình')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy quy trình')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '5. Quy Trình Công Ty',
                'verbose_name_plural': '5. Quy Trình Công Ty',
            },
        ),
        migrations.CreateModel(
            name='Quydinhphongban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenquydinh', models.CharField(default='', max_length=255, verbose_name='Tên quy định')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung quy định')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy quy định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng ban áp dụng')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '2. Quy Định Phòng Ban',
                'verbose_name_plural': '2. Quy Định Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Quydinhcongty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenquydinh', models.CharField(default='', max_length=255, verbose_name='Tên quy định')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung quy định')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy quy định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '1. Quy Định Công Ty',
                'verbose_name_plural': '1. Quy Định Công Ty',
            },
        ),
        migrations.CreateModel(
            name='Chedophongban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenchedo', models.CharField(default='', max_length=255, verbose_name='Tên Chế Độ')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Chế Độ ')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy Chế Độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng ban áp dụng')),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '4. Chế Độ Phòng Ban',
                'verbose_name_plural': '4. Chế Độ Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Chedocongty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenchedo', models.CharField(default='', max_length=255, verbose_name='Tên Chế Độ')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội Dung Chế Độ ')),
                ('hienthi', models.BooleanField(verbose_name='Check : Cho hiển thị  - Uncheck : Tắt hiển thị')),
                ('huy', models.BooleanField(verbose_name='Hủy Chế Độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Tác Giả')),
            ],
            options={
                'verbose_name': '3. Chế Độ Công Ty',
                'verbose_name_plural': '3. Chế Độ Công Ty',
            },
        ),
    ]
