# Generated by Django 3.2.7 on 2021-09-20 15:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdqttb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chedocongty',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filechedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AddField(
            model_name='chedophongban',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filechedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AlterField(
            model_name='chedocongty',
            name='noidung',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội Dung Chế Độ '),
        ),
        migrations.AlterField(
            model_name='chedophongban',
            name='noidung',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội Dung Chế Độ '),
        ),
    ]
