# Generated by Django 3.2.7 on 2021-09-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdqttb', '0002_auto_20210920_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='quydinhcongty',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filecquydinhhedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AddField(
            model_name='quydinhphongban',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filecquydinhhedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AddField(
            model_name='quytrinhcongty',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filecquydinhhedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AddField(
            model_name='quytrinhphongban',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filecquydinhhedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='filecquydinhhedocongty/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
    ]
