# Generated by Django 3.2.3 on 2021-09-17 08:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Khachhanglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhachhang', models.CharField(default='', max_length=255, verbose_name='Tên Khách Hàng')),
                ('diachikh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Địa Chỉ Khách Hàng')),
                ('tencongtrinh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tên Công Trình')),
                ('diachicongtrinh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Địa Chỉ Công Trình')),
                ('hangmuc', models.CharField(choices=[('0', 'Hàng Hóa'), ('1', ' Lắp Đặt'), ('2', ' Phân phối Lắp Đặt'), ('3', 'Dịch Vụ')], max_length=20, verbose_name='Hạng Mục Hợp Đồng')),
                ('noidung', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('baogia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Báo Giá')),
                ('thuongthaohopdong', models.BooleanField(blank=True, default=False, null=True, verbose_name='Thương Thảo Hợp Đồng')),
                ('kyhopdong', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ký Hợp Đồng')),
                ('huytheo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Hủy Theo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien')),
                ('phongban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KHÁCH HÀNG LỚN',
                'verbose_name_plural': 'KHÁCH HÀNG LỚN',
            },
        ),
    ]
