# Generated by Django 3.2.7 on 2021-10-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BHcassper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_Casper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BHcassper.date_casper')),
            ],
            options={
                'verbose_name': 'Serial Casper ',
                'verbose_name_plural': 'Serial Casper ',
            },
        ),
    ]
