# Generated by Django 3.2.7 on 2021-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BHcassper', '0002_serial_casper'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial_casper',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
