# Generated by Django 3.2.7 on 2021-10-07 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BHcassper', '0003_serial_casper_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial_casper',
            name='date',
        ),
        migrations.AddField(
            model_name='serial_casper',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serial_casper',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Date_Casper',
        ),
    ]
