# Generated by Django 3.2.7 on 2021-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BHcassper', '0004_auto_20211007_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_Casper_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('active', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ĐẦU VÀO ',
                'verbose_name_plural': 'ĐẦU VÀO',
                'ordering': ['active'],
            },
        ),
        migrations.AlterModelOptions(
            name='serial_casper',
            options={'ordering': ['active'], 'verbose_name': 'ĐẦU VÀO ', 'verbose_name_plural': 'ĐẦU VÀO'},
        ),
    ]
