# Generated by Django 3.2.7 on 2021-10-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BHcassper', '0005_auto_20211008_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial_casper_out',
            options={'ordering': ['active'], 'verbose_name': 'ĐẦU RA ', 'verbose_name_plural': 'ĐẦU RA'},
        ),
    ]
