# Generated by Django 3.2.3 on 2021-09-17 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xinphep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaynghi', models.DateField(default=datetime.date.today, verbose_name='Ngày Nghỉ Phép')),
                ('ngaylamlai', models.DateField(verbose_name='Ngày đi làm lại ')),
                ('lydo', models.CharField(default='', max_length=1000, verbose_name='Lý Do Xin Nghỉ')),
                ('guiduyet', models.CharField(choices=[('1', 'Gửi Sếp'), ('2', ' Chỉ Gửi Trưởng Phòng')], max_length=20, verbose_name=' Gửi Duyệt')),
                ('sep_duyet', models.BooleanField()),
                ('tp_duyet', models.BooleanField()),
                ('huy', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.nhanvien', verbose_name='Nhân Viên ')),
            ],
            options={
                'verbose_name': ' XIN NGHỈ PHÉP ',
                'verbose_name_plural': ' XIN NGHỈ PHÉP',
            },
        ),
    ]
