# Generated by Django 3.2.3 on 2021-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0002_xinphep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinphep',
            name='huy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xinphep',
            name='sep_duyet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xinphep',
            name='tp_duyet',
            field=models.BooleanField(default=False),
        ),
    ]
