# Generated by Django 3.2.7 on 2021-09-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0003_auto_20210918_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Ảnh chân dung'),
        ),
    ]
