# Generated by Django 3.2.7 on 2021-09-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0004_alter_nhanvien_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='cmnd_1',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Ảnh mặt trước CMND/CCID'),
        ),
    ]
