# Generated by Django 3.2.7 on 2021-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0005_alter_nhanvien_cmnd_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiemvecxincovid',
            options={'verbose_name': 'TIÊM VẮC  XIN COVID ', 'verbose_name_plural': 'TIÊM VẮC XIN COVID '},
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='vitricongviec',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Vị Trí Công Việc'),
        ),
    ]
