# Generated by Django 3.2.7 on 2021-09-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0006_auto_20210920_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='motacongviec',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='motacongviec/', verbose_name='Upload file (có thể đẻ trông)'),
        ),
    ]
