# Generated by Django 3.2.7 on 2021-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0007_motacongviec_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baohiemxahoi',
            name='noidangky',
            field=models.CharField(blank=True, choices=[('BHXH Hóc Môn', 'BHXH Hóc Môn'), ('BHXH Quận 3', 'BHXH Quận 3')], max_length=255, null=True, verbose_name='Địa chỉ đăng ký'),
        ),
    ]
