# Generated by Django 3.2.7 on 2021-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0008_alter_baohiemxahoi_noidangky'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baohiemxahoi',
            options={'ordering': ['id'], 'verbose_name': '3. BẢO HIỂM XÃ HỘI', 'verbose_name_plural': '3. BẢO HIỂM XÃ HỘI'},
        ),
        migrations.AlterModelOptions(
            name='baohiemyte',
            options={'ordering': ['id'], 'verbose_name': '4. BẢO HIỂM Y TẾ', 'verbose_name_plural': '4. BẢO HIỂM Y TẾ'},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'ordering': ['id'], 'verbose_name': '2. NHÂN VIÊN', 'verbose_name_plural': '2. NHÂN VIÊN'},
        ),
        migrations.AlterModelOptions(
            name='tiemvecxincovid',
            options={'ordering': ['id'], 'verbose_name': 'TIÊM VẮC  XIN COVID ', 'verbose_name_plural': 'TIÊM VẮC XIN COVID '},
        ),
        migrations.AddField(
            model_name='xinphep',
            name='lienlac',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Liên Lạc Khẩn Cấp '),
        ),
    ]
