# Generated by Django 3.2.7 on 2021-09-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0009_auto_20210924_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinphep',
            name='phongban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qlns.phongban', verbose_name='Phòng Ban'),
        ),
    ]
