# Generated by Django 3.2.7 on 2021-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0011_auto_20210925_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='sos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Điện Thoại Khẩn Cấp'),
        ),
    ]
