# Generated by Django 3.2.7 on 2021-09-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0013_auto_20210929_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chucvu_congviec',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chucvu_congviec',
            name='updated_at',
        ),
    ]
