# Generated by Django 3.2.7 on 2021-09-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0014_auto_20210929_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phanquyen',
        ),
    ]
