# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0015_delete_phanquyen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chucvu_congviec',
            options={'verbose_name': 'NHÂN VIÊN CHỨC VỤ', 'verbose_name_plural': 'NHÂN VIÊN CHỨC VỤ'},
        ),
    ]
