# Generated by Django 3.2.7 on 2021-09-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0016_alter_chucvu_congviec_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filegiaichis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, default='', null=True, upload_to='giaichi/')),
                ('giaichi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlns.giaichi')),
            ],
            options={
                'verbose_name': 'FILE GIAI CHI',
                'verbose_name_plural': 'FILE GIAI CHI',
            },
        ),
    ]
