# Generated by Django 3.2.7 on 2021-10-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0019_alter_chucvu_congviec_nhanvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaichi',
            name='filegiaichi',
        ),
    ]
