# Generated by Django 3.2.3 on 2021-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('mucdo', models.CharField(choices=[('0', 'rất gấp'), ('1', 'gấp'), ('2', 'không gấp')], max_length=20, verbose_name='Mức Độ')),
                ('ngayhoanthanh', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
