# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permistions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chucnangapp', models.CharField(default='', max_length=255, verbose_name='Ten app_chuc nang ')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permistions ',
                'verbose_name_plural': 'Permistions',
            },
        ),
    ]
