# Generated by Django 3.2.7 on 2021-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permistion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenchucnang', models.CharField(default='', max_length=255, verbose_name='Ten chuc nang ')),
                ('noidung', models.TextField(default='', max_length=1000, verbose_name='Noi Dung')),
            ],
            options={
                'verbose_name': 'Cai Dat  ',
                'verbose_name_plural': 'Cai Dat',
            },
        ),
    ]
